"""Write the starter knowledge base into data/kb/.

Kept as a script rather than loose .txt files so the corpus is reproducible and its
provenance is obvious. The domain (information retrieval / NLP) is deliberate: it makes
hand-written test queries easy to reason about, and it includes topics with thin coverage
so the restoration and abstain branches can be exercised on real data.

Usage:  python scripts/seed_kb.py [--force]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
KB_DIR = REPO_ROOT / "data" / "kb"

DOCUMENTS: dict[str, str] = {
    "tfidf": """TF-IDF stands for term frequency inverse document frequency. It weights each term by how often it appears in a document, scaled down by how common that term is across the whole collection. Terms that appear in nearly every document, such as "the" or "and", receive weights close to zero. The scheme was introduced by Karen Sparck Jones in 1972 as a statistical interpretation of term specificity. TF-IDF remains a strong lexical baseline for retrieval despite being decades old.""",
    "bm25": """BM25 is a probabilistic ranking function used by search engines to estimate the relevance of documents to a query. It extends TF-IDF with two corrections: term frequency saturation, so repeating a word many times yields diminishing returns, and document length normalisation, so long documents are not unfairly favoured. The function has two tunable parameters, k1 and b, which control saturation and length normalisation respectively. Typical default values are k1 around 1.2 and b around 0.75. BM25 frequently matches or beats dense retrievers on out-of-domain benchmarks.""",
    "dense_retrieval": """Dense retrieval encodes queries and documents into fixed-length vectors and ranks by similarity in that shared space. Unlike lexical methods it can match paraphrases that share no vocabulary, so a query about "car" can retrieve a passage about "automobile". Dense retrievers are typically trained with contrastive objectives that pull matching query-document pairs together and push mismatched pairs apart. Their main weakness is out-of-domain generalisation, where they often underperform BM25. Hybrid systems combine both signals to get the benefits of each.""",
    "embeddings": """An embedding is a dense vector representation of text in which semantic similarity corresponds to geometric proximity. Sentence embeddings are commonly produced by mean-pooling the token representations from a transformer encoder. Cosine similarity is the usual comparison metric because it ignores vector magnitude and compares only direction. The all-MiniLM-L6-v2 model produces 384-dimensional embeddings and is widely used for its speed. Embedding quality dominates retrieval quality in dense systems.""",
    "vector_index": """A vector index accelerates nearest-neighbour search over embedding collections. Exact search compares the query against every stored vector, which is linear in collection size but always returns the true nearest neighbours. Approximate methods such as HNSW and IVF trade a small amount of recall for large speed gains. For collections below roughly ten thousand vectors, exact brute-force search is usually fast enough and avoids the tuning burden entirely. Choosing an approximate index too early is a common source of unexplained recall loss.""",
    "rag": """Retrieval-augmented generation combines a retrieval system with a generative language model. Retrieved passages are inserted into the model's prompt as context, letting the model ground its answer in external evidence rather than parametric memory alone. This reduces hallucination and allows the knowledge base to be updated without retraining the model. The cost is prompt length: every retrieved passage consumes context tokens. RAG was introduced by Lewis and colleagues in 2020.""",
    "context_window": """The context window is the maximum number of tokens a language model can attend over in a single forward pass. Attention cost grows quadratically with sequence length, so long contexts are expensive in both time and memory. Retrieval-augmented systems consume context aggressively because every retrieved passage occupies space that could otherwise hold reasoning or conversation history. Models also exhibit a "lost in the middle" effect, attending less reliably to information placed in the centre of a long context. Shorter, better-targeted context often outperforms simply retrieving more.""",
    "prompt_compression": """Prompt compression reduces the token cost of a prompt while preserving the information the model needs. Extractive compression selects a subset of the original sentences and discards the rest, so every surviving token is verbatim source text. Abstractive compression rewrites the content into a shorter paraphrase, achieving higher compression ratios at the cost of introducing text the source never contained. Extractive methods are straightforward to reverse because the discarded material can be reinstated exactly. Abstractive methods cannot be inverted from their output alone.""",
    "uncertainty_estimation": """Uncertainty estimation asks how confident a model is in its own output. Aleatoric uncertainty arises from noise inherent in the data, while epistemic uncertainty reflects gaps in what the model has learned. Common practical estimators include token-level log probabilities, disagreement across sampled generations, and ensemble variance. Retrieval systems can also derive a confidence signal from similarity scores and the margin between the top result and its runner-up. A large margin suggests the top result is decisively better, whereas a narrow margin suggests the ranking is unstable.""",
    "calibration": """A model is calibrated when its stated confidence matches its observed accuracy. If a calibrated system assigns 0.8 confidence to a set of predictions, roughly 80 percent of them should be correct. Large language models are frequently overconfident, especially after instruction tuning. Expected calibration error measures the average gap between confidence and accuracy across confidence bins. Calibration matters for selective prediction, where a system must decide when to answer and when to abstain.""",
    "selective_prediction": """Selective prediction allows a model to decline to answer when its confidence falls below a threshold. The tradeoff is measured by a risk-coverage curve: coverage is the fraction of inputs answered, and risk is the error rate on those answers. Lowering the threshold raises coverage but usually raises risk as well. Abstention is valuable in high-stakes settings where a wrong answer costs more than no answer. A system that abstains well is more trustworthy than one with marginally higher raw accuracy.""",
    "hallucination": """Hallucination refers to fluent model output that is not supported by any source. Intrinsic hallucinations contradict the provided context, while extrinsic hallucinations introduce claims the context simply does not address. Grounding generation in retrieved evidence reduces but does not eliminate the problem. Insufficient evidence is a common trigger: when context does not answer the question, models often fill the gap rather than declining. Verifying each claim against evidence before emitting an answer is a direct mitigation.""",
    "nli": """Natural language inference classifies the relationship between a premise and a hypothesis as entailment, contradiction, or neutral. In fact-verification pipelines the retrieved evidence serves as the premise and the claim under test as the hypothesis. The probability assigned to the entailment class functions as a continuous support score rather than a binary judgment. NLI models are considerably smaller and faster than generative models, making them practical for scoring many claim-evidence pairs. The MultiNLI corpus is the standard training set for these models.""",
    "claim_decomposition": """Claim decomposition breaks a complex statement into atomic factual units that can be verified independently. A sentence asserting two separate facts should become two claims, since evidence may support one and not the other. Decomposition can be applied to a user's question to produce sub-questions, or to a draft answer to produce checkable assertions. Verifying a draft answer checks exactly what will be shown to the user, but risks inheriting hallucinated claims. Decomposing the query instead avoids that circularity but may not cover everything the final answer asserts.""",
    "attribution": """Attribution links each statement in a generated answer back to the specific evidence that supports it. Citation-level attribution points at a whole document, while span-level attribution points at exact character offsets within it. Span-level attribution allows a reader to verify a claim without rereading the source. Storing character offsets rather than copied text also means the original can always be recovered exactly. Attribution and reversible compression share this same underlying requirement.""",
    "evaluation_metrics": """Retrieval quality is commonly measured with recall at k, mean reciprocal rank, and normalised discounted cumulative gain. Recall at k asks whether a relevant document appears anywhere in the top k results. Mean reciprocal rank rewards placing the first relevant result as high as possible. Generation quality is harder to measure automatically, and exact-match or F1 against reference answers correlates only loosely with human judgment. Reporting token cost alongside quality is essential whenever a system claims an efficiency gain.""",
    "ablation": """An ablation study removes or replaces one component of a system at a time to measure that component's contribution. Without ablations it is impossible to tell whether a reported gain comes from the proposed mechanism or from an unrelated implementation detail. A well-designed ablation changes exactly one variable while holding everything else fixed. Reviewers routinely reject papers whose headline improvement is not isolated by ablation. Building components behind a common interface makes ablations cheap to run later.""",
    "reproducibility": """Reproducibility requires that an experiment can be rerun to produce the same numbers. Fixing random seeds, pinning dependency versions, and recording configuration alongside results are the minimum requirements. Greedy decoding removes sampling variance from generation and should be preferred when measuring a system rather than demonstrating it. Logging intermediate scores, not only final outputs, makes failures diagnosable after the fact. Configuration stored in files rather than embedded in code is far easier to record and vary.""",
    "chunking": """Chunking splits documents into retrievable units. Chunks that are too small lack the context needed to interpret them, while chunks that are too large dilute the embedding and waste prompt tokens on irrelevant material. Sentence-level chunking is a common default for evidence-oriented tasks. Preserving each chunk's character offsets into its source document allows the exact original text to be recovered at any time. Without offsets, a chunk is merely a copy and its relationship to the source is lost.""",
    "reranking": """Reranking applies a slower, more accurate model to the shortlist produced by fast first-stage retrieval. Cross-encoders score a query and document jointly, letting every query token attend to every document token, which is far more accurate than comparing independent embeddings. The cost is that cross-encoders cannot be precomputed, so they only run over a shortlist. A typical configuration retrieves one hundred candidates and reranks them down to five. Reranking usually improves precision substantially at modest latency cost.""",
    "knowledge_cutoff": """A language model's parametric knowledge is frozen at its training cutoff date. Facts that changed after that date remain wrong in the model's weights regardless of how it is prompted. Retrieval addresses this by supplying current information at inference time. Keeping the knowledge base current is therefore a maintenance task rather than a retraining task. Conflicts between retrieved evidence and parametric memory are a known failure mode, and models do not always defer to the provided evidence.""",
    "tokenization": """Tokenization converts raw text into the discrete units a model processes. Byte-pair encoding merges frequent character pairs into single tokens, keeping vocabularies compact while still representing any string. Token counts are not proportional to word counts, and they vary substantially between tokenizers for the same text. Estimating token cost from character counts is convenient but imprecise, and any efficiency claim should be measured with the actual tokenizer. Different models can report meaningfully different token counts for identical input.""",
    "caching": """Caching stores the result of an expensive computation so it need not be repeated. Embedding caches are keyed by both the model identifier and a hash of the input, so a change to either produces a miss rather than a stale hit. Serving a stale cache entry after the underlying data has changed is a common and hard-to-diagnose bug. Prompt caching at the model provider level reduces cost for repeated prefixes. Cache invalidation strategy matters more than cache hit rate.""",
    "latency": """End-to-end latency in a retrieval-augmented system is the sum of embedding, search, reranking, and generation time. Generation typically dominates, because tokens are produced sequentially. Reducing prompt length lowers time to first token as well as cost. Batching improves throughput but does not improve the latency of any individual request. Measuring each stage separately is necessary to know where optimisation effort will actually pay off.""",
}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--force", action="store_true", help="overwrite existing documents"
    )
    args = parser.parse_args()

    KB_DIR.mkdir(parents=True, exist_ok=True)
    written, skipped = 0, 0
    for doc_id, text in DOCUMENTS.items():
        path = KB_DIR / f"{doc_id}.txt"
        if path.exists() and not args.force:
            skipped += 1
            continue
        path.write_text(text.strip() + "\n", encoding="utf-8")
        written += 1

    print(f"wrote {written} documents to {KB_DIR}" + (f", skipped {skipped} existing" if skipped else ""))
    if skipped and not args.force:
        print("re-run with --force to overwrite")
    return 0


if __name__ == "__main__":
    sys.exit(main())
